In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/plant-growth-data-classification/plant_growth_data.csv

In [4]:
#importing the file
train = pd.read_csv('/kaggle/input/plant-growth-data-classification/plant_growth_data.csv')

In [5]:
#importing the file
train.head()

,Soil_Type,Sunlight_Hours,Water_Frequency,Fertilizer_Type,Temperature,Humidity,Growth_Milestone
0,loam,5.192294,bi-weekly,chemical,31.719602,61.591861,0
1,sandy,4.033133,weekly,organic,28.919484,52.422276,1
2,loam,8.892769,bi-weekly,none,23.179059,44.660539,0
3,loam,8.241144,bi-weekly,none,18.465886,46.433227,0
4,sandy,8.374043,bi-weekly,organic,18.128741,63.625923,0

In [6]:
#viewing dataset
train.head(12)

,Soil_Type,Sunlight_Hours,Water_Frequency,Fertilizer_Type,Temperature,Humidity,Growth_Milestone
0,loam,5.192294,bi-weekly,chemical,31.719602,61.591861,0
1,sandy,4.033133,weekly,organic,28.919484,52.422276,1
2,loam,8.892769,bi-weekly,none,23.179059,44.660539,0
3,loam,8.241144,bi-weekly,none,18.465886,46.433227,0
4,sandy,8.374043,bi-weekly,organic,18.128741,63.625923,0
5,sandy,8.627622,bi-weekly,none,20.004858,67.618726,0
6,loam,4.444268,daily,organic,25.984533,69.578952,1
7,clay,6.150794,daily,organic,29.291918,69.480907,0
8,loam,4.695214,bi-weekly,none,28.203948,34.560305,1
9,loam,9.178621,weekly,organic,20.598678,54.721015,1
10,loam,7.739789,daily,none,34.097306,32.877938,0
11,loam,5.985388,bi-weekly,chemical,29.757938,57.476444,0

In [7]:
#viewing the last 5 rows
train.tail()

,Soil_Type,Sunlight_Hours,Water_Frequency,Fertilizer_Type,Temperature,Humidity,Growth_Milestone
188,sandy,5.652,daily,none,28.0,70.2,0
189,clay,7.528,weekly,chemical,30.5,60.1,1
190,loam,4.934,bi-weekly,none,24.5,61.7,0
191,sandy,8.273,daily,organic,27.9,69.5,1
192,clay,6.732,weekly,none,21.7,56.9,0

In [12]:
#viewing the centre rows
train.iloc[89:96]

,Soil_Type,Sunlight_Hours,Water_Frequency,Fertilizer_Type,Temperature,Humidity,Growth_Milestone
89,sandy,6.206699,daily,none,31.529149,70.689751,1
90,sandy,7.793835,weekly,organic,21.400992,64.236559,1
91,sandy,7.801178,daily,none,32.910465,38.130847,0
92,sandy,7.214648,weekly,none,22.784034,75.546359,0
93,loam,4.541739,daily,chemical,15.216753,71.126862,1
94,sandy,9.011815,weekly,none,33.107640,77.489996,0
95,sandy,5.924680,bi-weekly,chemical,16.825734,66.285975,0

In [13]:
#getting the shape of dataset
print('the dataset has',train.shape[0],'no of rows')
print('the dataset has',train.shape[1],'no of columns')

the dataset has 193 no of rows
the dataset has 7 no of columns

In [16]:
#checking the missing values
train.isnull().sum()

Soil_Type           0
Sunlight_Hours      0
Water_Frequency     0
Fertilizer_Type     0
Temperature         0
Humidity            0
Growth_Milestone    0
dtype: int64

In [18]:
#checking the duplicate values
train.duplicated().sum()

0